blank_issues_enabled: false

contact_links:
  - name: Questions & support
    url: https://github.com/XSaitoKungX/advanced-modmail/discussions
    about: Use GitHub Discussions for questions, support and general conversations.
