import { migrate } from "drizzle-orm/postgres-js/migrator";
import type { DatabaseClient } from "./client.js";

// Migration SQL lives next to the schema, resolved relative to the process
// working directory (the repository root in every documented runtime).
export const MIGRATIONS_FOLDER = "src/database/migrations";

// Forward-only: migrations are generated by drizzle-kit, reviewed in Git,
// and never edited after merge. Rollbacks are new forward migrations.
// Bootstrap does NOT auto-migrate; operators run `pnpm db:migrate`
// (drizzle-kit) so schema changes stay deliberate. This entry point exists
// for test setup and future controlled automation.
export async function runMigrations(
  client: DatabaseClient,
  migrationsFolder: string = MIGRATIONS_FOLDER,
): Promise<void> {
  await migrate(client.db, { migrationsFolder });
}
